#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : obs-studio
Version  : 27.2.4
Release  : 29
URL      : https://github.com/obsproject/obs-studio/archive/27.2.4/obs-studio-27.2.4.tar.gz
Source0  : https://github.com/obsproject/obs-studio/archive/27.2.4/obs-studio-27.2.4.tar.gz
Summary  : OBS Studio Library
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-2.0 LGPL-2.1 MIT
Requires: obs-studio-bin = %{version}-%{release}
Requires: obs-studio-data = %{version}-%{release}
Requires: obs-studio-filemap = %{version}-%{release}
Requires: obs-studio-lib = %{version}-%{release}
Requires: obs-studio-license = %{version}-%{release}
BuildRequires : Vulkan-Headers-dev Vulkan-Loader-dev Vulkan-Tools
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : curl-dev
BuildRequires : extra-cmake-modules pkgconfig(egl)
BuildRequires : extra-cmake-modules pkgconfig(libpulse)
BuildRequires : extra-cmake-modules pkgconfig(wayland-client)
BuildRequires : extra-cmake-modules pkgconfig(x11-xcb)
BuildRequires : extra-cmake-modules pkgconfig(xcb) xcb-util-cursor-dev xcb-util-image-dev xcb-util-keysyms-dev xcb-util-renderutil-dev xcb-util-wm-dev xcb-util-dev
BuildRequires : freetype-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : mesa-dev
BuildRequires : not-ffmpeg-dev
BuildRequires : pipewire-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(jansson)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libpci)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libvlc)
BuildRequires : pkgconfig(luajit)
BuildRequires : pkgconfig(speexdsp)
BuildRequires : pkgconfig(vulkan)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-server)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(zlib)
BuildRequires : python3-dev
BuildRequires : qtbase-dev
BuildRequires : qtsvg-dev
BuildRequires : qtx11extras-dev
BuildRequires : speex-dev
BuildRequires : speexdsp-dev
BuildRequires : swig
BuildRequires : texlive
BuildRequires : v4l-utils-dev
BuildRequires : zlib-dev
Patch1: build-without-libx264.patch
Patch2: obs-studio-change-default-config-to-ffmpeg.patch

%description
RNNoise is a noise suppression library based on a recurrent neural network.
To compile, just type:
% ./autogen.sh
% ./configure
% make

%package bin
Summary: bin components for the obs-studio package.
Group: Binaries
Requires: obs-studio-data = %{version}-%{release}
Requires: obs-studio-license = %{version}-%{release}
Requires: obs-studio-filemap = %{version}-%{release}

%description bin
bin components for the obs-studio package.


%package data
Summary: data components for the obs-studio package.
Group: Data

%description data
data components for the obs-studio package.


%package dev
Summary: dev components for the obs-studio package.
Group: Development
Requires: obs-studio-lib = %{version}-%{release}
Requires: obs-studio-bin = %{version}-%{release}
Requires: obs-studio-data = %{version}-%{release}
Provides: obs-studio-devel = %{version}-%{release}
Requires: obs-studio = %{version}-%{release}

%description dev
dev components for the obs-studio package.


%package filemap
Summary: filemap components for the obs-studio package.
Group: Default

%description filemap
filemap components for the obs-studio package.


%package lib
Summary: lib components for the obs-studio package.
Group: Libraries
Requires: obs-studio-data = %{version}-%{release}
Requires: obs-studio-license = %{version}-%{release}
Requires: obs-studio-filemap = %{version}-%{release}

%description lib
lib components for the obs-studio package.


%package license
Summary: license components for the obs-studio package.
Group: Default

%description license
license components for the obs-studio package.


%prep
%setup -q -n obs-studio-27.2.4
cd %{_builddir}/obs-studio-27.2.4
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648618576
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto -march=x86-64-v3 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -march=x86-64-v3 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -march=x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto -march=x86-64-v3 "
%cmake .. -DOBS_MULTIARCH_SUFFIX=64 -DBUILD_BROWSER=OFF -DBUILD_VST=OFF
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v3 -ffat-lto-objects -flto=auto -march=x86-64-v3 -mtune=skylake "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -ffat-lto-objects -flto=auto -march=x86-64-v3 -mtune=skylake "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -ffat-lto-objects -flto=auto -march=x86-64-v3 -mtune=skylake "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v3 -ffat-lto-objects -flto=auto -march=x86-64-v3 -mtune=skylake "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake .. -DOBS_MULTIARCH_SUFFIX=64 -DBUILD_BROWSER=OFF -DBUILD_VST=OFF
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1648618576
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/obs-studio
cp %{_builddir}/obs-studio-27.2.4/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/obs-studio-27.2.4/UI/data/license/gplv2.txt %{buildroot}/usr/share/package-licenses/obs-studio/53ae571e8630014de689edff14f755f16e5db8ed
cp %{_builddir}/obs-studio-27.2.4/UI/data/license/gplv2.txt %{buildroot}/usr/share/package-licenses/obs-studio/53ae571e8630014de689edff14f755f16e5db8ed
cp %{_builddir}/obs-studio-27.2.4/deps/jansson/LICENSE %{buildroot}/usr/share/package-licenses/obs-studio/26a708b97cbb50e3fce8078dd21d65c8fdd5a605
cp %{_builddir}/obs-studio-27.2.4/deps/json11/LICENSE.txt %{buildroot}/usr/share/package-licenses/obs-studio/d40d61b8fa8ecae46da12bd1fce4162af02cff8c
cp %{_builddir}/obs-studio-27.2.4/deps/libcaption/LICENSE.txt %{buildroot}/usr/share/package-licenses/obs-studio/ac86b1d99268507a73261982375a5f47541247b1
cp %{_builddir}/obs-studio-27.2.4/deps/w32-pthreads/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/0aeece1a03fbe9860ded71b2e17445209ad33c77
cp %{_builddir}/obs-studio-27.2.4/deps/w32-pthreads/COPYING.LIB %{buildroot}/usr/share/package-licenses/obs-studio/f6c7aa5a4f602a093c50a1d3328d1cb873ffdfc0
cp %{_builddir}/obs-studio-27.2.4/plugins/mac-syphon/data/syphon_license.txt %{buildroot}/usr/share/package-licenses/obs-studio/6f68b53b3b12e5b75f296c54be785bc63e553d53
cp %{_builddir}/obs-studio-27.2.4/plugins/obs-filters/rnnoise/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/5f8e73e1f293d0f127c2bcad2ab6fc5fa2a58139
cp %{_builddir}/obs-studio-27.2.4/plugins/obs-outputs/librtmp/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/6138ce06f16aef800693fb256090749acbabd038
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot}/usr/share/clear/optimized-elf/ %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/obs-scripting/obspython.py

%files bin
%defattr(-,root,root,-)
/usr/bin/obs
/usr/bin/obs-ffmpeg-mux
/usr/share/clear/optimized-elf/bin*

%files data
%defattr(-,root,root,-)
/usr/share/applications/com.obsproject.Studio.desktop
/usr/share/icons/hicolor/128x128/apps/com.obsproject.Studio.png
/usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png
/usr/share/icons/hicolor/512x512/apps/com.obsproject.Studio.png
/usr/share/icons/hicolor/scalable/apps/com.obsproject.Studio.svg
/usr/share/metainfo/com.obsproject.Studio.appdata.xml
/usr/share/obs/libobs/area.effect
/usr/share/obs/libobs/bicubic_scale.effect
/usr/share/obs/libobs/bilinear_lowres_scale.effect
/usr/share/obs/libobs/default.effect
/usr/share/obs/libobs/default_rect.effect
/usr/share/obs/libobs/deinterlace_base.effect
/usr/share/obs/libobs/deinterlace_blend.effect
/usr/share/obs/libobs/deinterlace_blend_2x.effect
/usr/share/obs/libobs/deinterlace_discard.effect
/usr/share/obs/libobs/deinterlace_discard_2x.effect
/usr/share/obs/libobs/deinterlace_linear.effect
/usr/share/obs/libobs/deinterlace_linear_2x.effect
/usr/share/obs/libobs/deinterlace_yadif.effect
/usr/share/obs/libobs/deinterlace_yadif_2x.effect
/usr/share/obs/libobs/format_conversion.effect
/usr/share/obs/libobs/lanczos_scale.effect
/usr/share/obs/libobs/opaque.effect
/usr/share/obs/libobs/premultiplied_alpha.effect
/usr/share/obs/libobs/repeat.effect
/usr/share/obs/libobs/solid.effect
/usr/share/obs/obs-plugins/decklink-captions/.keepme
/usr/share/obs/obs-plugins/decklink-ouput-ui/.keepme
/usr/share/obs/obs-plugins/frontend-tools/locale/an-ES.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ar-SA.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/az-AZ.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ba-RU.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/bg-BG.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/bn-BD.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ca-ES.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/da-DK.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/de-DE.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/el-GR.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/en-US.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/eo-UY.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/es-ES.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/et-EE.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/eu-ES.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/fa-IR.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/fi-FI.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/fil-PH.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/fr-FR.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/gd-GB.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/gl-ES.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/he-IL.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/hi-IN.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/hr-HR.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/hu-HU.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/id-ID.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/it-IT.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ja-JP.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ka-GE.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ko-KR.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/lo-LA.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/lt-LT.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/mn-MN.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ms-MY.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/nb-NO.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/nl-NL.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/oc-FR.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/pl-PL.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/pt-BR.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/pt-PT.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ro-RO.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ru-RU.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/si-LK.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/sk-SK.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/sl-SI.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/sq-AL.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/sr-CS.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/sr-SP.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/sv-SE.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/szl-PL.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/ta-IN.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/th-TH.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/tl-PH.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/tr-TR.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/uk-UA.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/vi-VN.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/zh-CN.ini
/usr/share/obs/obs-plugins/frontend-tools/locale/zh-TW.ini
/usr/share/obs/obs-plugins/frontend-tools/scripts/clock-source.lua
/usr/share/obs/obs-plugins/frontend-tools/scripts/clock-source/dial.png
/usr/share/obs/obs-plugins/frontend-tools/scripts/clock-source/hour.png
/usr/share/obs/obs-plugins/frontend-tools/scripts/clock-source/minute.png
/usr/share/obs/obs-plugins/frontend-tools/scripts/clock-source/second.png
/usr/share/obs/obs-plugins/frontend-tools/scripts/countdown.lua
/usr/share/obs/obs-plugins/frontend-tools/scripts/instant-replay.lua
/usr/share/obs/obs-plugins/frontend-tools/scripts/pause-scene.lua
/usr/share/obs/obs-plugins/frontend-tools/scripts/url-text.py
/usr/share/obs/obs-plugins/image-source/locale/ar-SA.ini
/usr/share/obs/obs-plugins/image-source/locale/az-AZ.ini
/usr/share/obs/obs-plugins/image-source/locale/ba-RU.ini
/usr/share/obs/obs-plugins/image-source/locale/bg-BG.ini
/usr/share/obs/obs-plugins/image-source/locale/bn-BD.ini
/usr/share/obs/obs-plugins/image-source/locale/ca-ES.ini
/usr/share/obs/obs-plugins/image-source/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/image-source/locale/da-DK.ini
/usr/share/obs/obs-plugins/image-source/locale/de-DE.ini
/usr/share/obs/obs-plugins/image-source/locale/el-GR.ini
/usr/share/obs/obs-plugins/image-source/locale/en-GB.ini
/usr/share/obs/obs-plugins/image-source/locale/en-US.ini
/usr/share/obs/obs-plugins/image-source/locale/es-ES.ini
/usr/share/obs/obs-plugins/image-source/locale/et-EE.ini
/usr/share/obs/obs-plugins/image-source/locale/eu-ES.ini
/usr/share/obs/obs-plugins/image-source/locale/fa-IR.ini
/usr/share/obs/obs-plugins/image-source/locale/fi-FI.ini
/usr/share/obs/obs-plugins/image-source/locale/fil-PH.ini
/usr/share/obs/obs-plugins/image-source/locale/fr-FR.ini
/usr/share/obs/obs-plugins/image-source/locale/gd-GB.ini
/usr/share/obs/obs-plugins/image-source/locale/gl-ES.ini
/usr/share/obs/obs-plugins/image-source/locale/he-IL.ini
/usr/share/obs/obs-plugins/image-source/locale/hi-IN.ini
/usr/share/obs/obs-plugins/image-source/locale/hr-HR.ini
/usr/share/obs/obs-plugins/image-source/locale/hu-HU.ini
/usr/share/obs/obs-plugins/image-source/locale/id-ID.ini
/usr/share/obs/obs-plugins/image-source/locale/it-IT.ini
/usr/share/obs/obs-plugins/image-source/locale/ja-JP.ini
/usr/share/obs/obs-plugins/image-source/locale/ka-GE.ini
/usr/share/obs/obs-plugins/image-source/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/image-source/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/image-source/locale/ko-KR.ini
/usr/share/obs/obs-plugins/image-source/locale/lo-LA.ini
/usr/share/obs/obs-plugins/image-source/locale/lt-LT.ini
/usr/share/obs/obs-plugins/image-source/locale/mn-MN.ini
/usr/share/obs/obs-plugins/image-source/locale/ms-MY.ini
/usr/share/obs/obs-plugins/image-source/locale/nb-NO.ini
/usr/share/obs/obs-plugins/image-source/locale/nl-NL.ini
/usr/share/obs/obs-plugins/image-source/locale/nn-NO.ini
/usr/share/obs/obs-plugins/image-source/locale/oc-FR.ini
/usr/share/obs/obs-plugins/image-source/locale/pa-IN.ini
/usr/share/obs/obs-plugins/image-source/locale/pl-PL.ini
/usr/share/obs/obs-plugins/image-source/locale/pt-BR.ini
/usr/share/obs/obs-plugins/image-source/locale/pt-PT.ini
/usr/share/obs/obs-plugins/image-source/locale/ro-RO.ini
/usr/share/obs/obs-plugins/image-source/locale/ru-RU.ini
/usr/share/obs/obs-plugins/image-source/locale/si-LK.ini
/usr/share/obs/obs-plugins/image-source/locale/sk-SK.ini
/usr/share/obs/obs-plugins/image-source/locale/sl-SI.ini
/usr/share/obs/obs-plugins/image-source/locale/sr-CS.ini
/usr/share/obs/obs-plugins/image-source/locale/sr-SP.ini
/usr/share/obs/obs-plugins/image-source/locale/sv-SE.ini
/usr/share/obs/obs-plugins/image-source/locale/ta-IN.ini
/usr/share/obs/obs-plugins/image-source/locale/th-TH.ini
/usr/share/obs/obs-plugins/image-source/locale/tl-PH.ini
/usr/share/obs/obs-plugins/image-source/locale/tr-TR.ini
/usr/share/obs/obs-plugins/image-source/locale/uk-UA.ini
/usr/share/obs/obs-plugins/image-source/locale/ur-PK.ini
/usr/share/obs/obs-plugins/image-source/locale/vi-VN.ini
/usr/share/obs/obs-plugins/image-source/locale/zh-CN.ini
/usr/share/obs/obs-plugins/image-source/locale/zh-TW.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/an-ES.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ar-SA.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/az-AZ.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ba-RU.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/bg-BG.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/bn-BD.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ca-ES.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/da-DK.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/de-DE.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/el-GR.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/en-US.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/es-ES.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/et-EE.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/eu-ES.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/fa-IR.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/fi-FI.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/fr-FR.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/gd-GB.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/gl-ES.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/he-IL.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/hi-IN.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/hr-HR.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/hu-HU.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/id-ID.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/it-IT.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ja-JP.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ka-GE.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ko-KR.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/lt-LT.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ms-MY.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/nb-NO.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/nl-NL.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/nn-NO.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/pl-PL.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/pt-BR.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/pt-PT.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ro-RO.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ru-RU.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/si-LK.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/sk-SK.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/sl-SI.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/sr-CS.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/sr-SP.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/sv-SE.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/szl-PL.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ta-IN.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/th-TH.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/tl-PH.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/tr-TR.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/uk-UA.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/ur-PK.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/vi-VN.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/zh-CN.ini
/usr/share/obs/obs-plugins/linux-alsa/locale/zh-TW.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ar-SA.ini
/usr/share/obs/obs-plugins/linux-capture/locale/az-AZ.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ba-RU.ini
/usr/share/obs/obs-plugins/linux-capture/locale/bg-BG.ini
/usr/share/obs/obs-plugins/linux-capture/locale/bn-BD.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ca-ES.ini
/usr/share/obs/obs-plugins/linux-capture/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/linux-capture/locale/da-DK.ini
/usr/share/obs/obs-plugins/linux-capture/locale/de-DE.ini
/usr/share/obs/obs-plugins/linux-capture/locale/el-GR.ini
/usr/share/obs/obs-plugins/linux-capture/locale/en-US.ini
/usr/share/obs/obs-plugins/linux-capture/locale/es-ES.ini
/usr/share/obs/obs-plugins/linux-capture/locale/et-EE.ini
/usr/share/obs/obs-plugins/linux-capture/locale/eu-ES.ini
/usr/share/obs/obs-plugins/linux-capture/locale/fa-IR.ini
/usr/share/obs/obs-plugins/linux-capture/locale/fi-FI.ini
/usr/share/obs/obs-plugins/linux-capture/locale/fil-PH.ini
/usr/share/obs/obs-plugins/linux-capture/locale/fr-FR.ini
/usr/share/obs/obs-plugins/linux-capture/locale/gd-GB.ini
/usr/share/obs/obs-plugins/linux-capture/locale/gl-ES.ini
/usr/share/obs/obs-plugins/linux-capture/locale/he-IL.ini
/usr/share/obs/obs-plugins/linux-capture/locale/hi-IN.ini
/usr/share/obs/obs-plugins/linux-capture/locale/hr-HR.ini
/usr/share/obs/obs-plugins/linux-capture/locale/hu-HU.ini
/usr/share/obs/obs-plugins/linux-capture/locale/id-ID.ini
/usr/share/obs/obs-plugins/linux-capture/locale/it-IT.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ja-JP.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ka-GE.ini
/usr/share/obs/obs-plugins/linux-capture/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/linux-capture/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ko-KR.ini
/usr/share/obs/obs-plugins/linux-capture/locale/lo-LA.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ms-MY.ini
/usr/share/obs/obs-plugins/linux-capture/locale/nb-NO.ini
/usr/share/obs/obs-plugins/linux-capture/locale/nl-NL.ini
/usr/share/obs/obs-plugins/linux-capture/locale/nn-NO.ini
/usr/share/obs/obs-plugins/linux-capture/locale/pl-PL.ini
/usr/share/obs/obs-plugins/linux-capture/locale/pt-BR.ini
/usr/share/obs/obs-plugins/linux-capture/locale/pt-PT.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ro-RO.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ru-RU.ini
/usr/share/obs/obs-plugins/linux-capture/locale/si-LK.ini
/usr/share/obs/obs-plugins/linux-capture/locale/sk-SK.ini
/usr/share/obs/obs-plugins/linux-capture/locale/sl-SI.ini
/usr/share/obs/obs-plugins/linux-capture/locale/sr-CS.ini
/usr/share/obs/obs-plugins/linux-capture/locale/sr-SP.ini
/usr/share/obs/obs-plugins/linux-capture/locale/sv-SE.ini
/usr/share/obs/obs-plugins/linux-capture/locale/szl-PL.ini
/usr/share/obs/obs-plugins/linux-capture/locale/ta-IN.ini
/usr/share/obs/obs-plugins/linux-capture/locale/tl-PH.ini
/usr/share/obs/obs-plugins/linux-capture/locale/tr-TR.ini
/usr/share/obs/obs-plugins/linux-capture/locale/uk-UA.ini
/usr/share/obs/obs-plugins/linux-capture/locale/vi-VN.ini
/usr/share/obs/obs-plugins/linux-capture/locale/zh-CN.ini
/usr/share/obs/obs-plugins/linux-capture/locale/zh-TW.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/an-ES.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ar-SA.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/az-AZ.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ba-RU.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/bg-BG.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/bn-BD.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ca-ES.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/da-DK.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/de-DE.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/el-GR.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/en-GB.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/en-US.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/eo-UY.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/es-ES.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/et-EE.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/eu-ES.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/fa-IR.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/fi-FI.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/fil-PH.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/fr-FR.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/gd-GB.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/gl-ES.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/he-IL.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/hi-IN.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/hr-HR.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/hu-HU.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/id-ID.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/it-IT.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ja-JP.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ka-GE.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ko-KR.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/lt-LT.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/mn-MN.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ms-MY.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/nb-NO.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/nl-NL.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/nn-NO.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/pl-PL.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/pt-BR.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/pt-PT.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ro-RO.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ru-RU.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/si-LK.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/sk-SK.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/sl-SI.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/sq-AL.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/sr-CS.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/sr-SP.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/sv-SE.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/szl-PL.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/ta-IN.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/th-TH.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/tl-PH.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/tr-TR.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/uk-UA.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/vi-VN.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/zh-CN.ini
/usr/share/obs/obs-plugins/linux-decklink/locale/zh-TW.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ar-SA.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/az-AZ.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ba-RU.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/bg-BG.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/bn-BD.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ca-ES.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/da-DK.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/de-DE.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/el-GR.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/en-US.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/es-ES.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/et-EE.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/eu-ES.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/fa-IR.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/fi-FI.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/fr-FR.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/gd-GB.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/gl-ES.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/he-IL.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/hi-IN.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/hr-HR.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/hu-HU.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/id-ID.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/it-IT.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ja-JP.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ka-GE.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ko-KR.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ms-MY.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/nb-NO.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/nl-NL.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/nn-NO.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/oc-FR.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/pl-PL.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/pt-BR.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/pt-PT.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ro-RO.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ru-RU.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/si-LK.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/sk-SK.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/sl-SI.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/sr-CS.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/sr-SP.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/sv-SE.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/szl-PL.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ta-IN.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/th-TH.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/tr-TR.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/uk-UA.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/ur-PK.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/vi-VN.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/zh-CN.ini
/usr/share/obs/obs-plugins/linux-pulseaudio/locale/zh-TW.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ar-SA.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/az-AZ.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ba-RU.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/bg-BG.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/bn-BD.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ca-ES.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/da-DK.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/de-DE.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/el-GR.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/en-GB.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/en-US.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/es-ES.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/et-EE.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/eu-ES.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/fa-IR.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/fi-FI.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/fil-PH.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/fr-FR.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/gd-GB.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/gl-ES.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/he-IL.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/hi-IN.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/hr-HR.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/hu-HU.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/id-ID.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/it-IT.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ja-JP.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ka-GE.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ko-KR.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ms-MY.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/nb-NO.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/nl-NL.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/oc-FR.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/pl-PL.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/pt-BR.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/pt-PT.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ro-RO.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ru-RU.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/si-LK.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/sk-SK.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/sl-SI.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/sr-CS.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/sr-SP.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/sv-SE.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/szl-PL.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ta-IN.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/tl-PH.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/tr-TR.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/uk-UA.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/ur-PK.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/vi-VN.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/zh-CN.ini
/usr/share/obs/obs-plugins/linux-v4l2/locale/zh-TW.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ar-SA.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ba-RU.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/bg-BG.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/bn-BD.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ca-ES.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/da-DK.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/de-DE.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/el-GR.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/en-GB.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/en-US.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/es-ES.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/et-EE.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/eu-ES.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/fa-IR.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/fi-FI.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/fil-PH.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/fr-FR.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/gd-GB.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/gl-ES.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/he-IL.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/hi-IN.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/hr-HR.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/hu-HU.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/id-ID.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/it-IT.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ja-JP.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ka-GE.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ko-KR.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ms-MY.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/nb-NO.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/nl-NL.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/nn-NO.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/oc-FR.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/pl-PL.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/pt-BR.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/pt-PT.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ro-RO.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ru-RU.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/si-LK.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/sk-SK.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/sl-SI.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/sr-CS.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/sr-SP.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/sv-SE.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/szl-PL.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ta-IN.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/th-TH.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/tl-PH.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/tr-TR.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/uk-UA.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/ur-PK.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/vi-VN.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/zh-CN.ini
/usr/share/obs/obs-plugins/obs-ffmpeg/locale/zh-TW.ini
/usr/share/obs/obs-plugins/obs-filters/LUTs/black_and_white.png
/usr/share/obs/obs-plugins/obs-filters/LUTs/grayscale.cube
/usr/share/obs/obs-plugins/obs-filters/LUTs/grayscale.png
/usr/share/obs/obs-plugins/obs-filters/LUTs/original.cube
/usr/share/obs/obs-plugins/obs-filters/LUTs/original.png
/usr/share/obs/obs-plugins/obs-filters/LUTs/posterize.png
/usr/share/obs/obs-plugins/obs-filters/LUTs/red_isolated.png
/usr/share/obs/obs-plugins/obs-filters/LUTs/teal_lows_orange_highs.png
/usr/share/obs/obs-plugins/obs-filters/blend_add_filter.effect
/usr/share/obs/obs-plugins/obs-filters/blend_mul_filter.effect
/usr/share/obs/obs-plugins/obs-filters/blend_sub_filter.effect
/usr/share/obs/obs-plugins/obs-filters/chroma_key_filter.effect
/usr/share/obs/obs-plugins/obs-filters/chroma_key_filter_v2.effect
/usr/share/obs/obs-plugins/obs-filters/color_correction_filter.effect
/usr/share/obs/obs-plugins/obs-filters/color_grade_filter.effect
/usr/share/obs/obs-plugins/obs-filters/color_key_filter.effect
/usr/share/obs/obs-plugins/obs-filters/color_key_filter_v2.effect
/usr/share/obs/obs-plugins/obs-filters/crop_filter.effect
/usr/share/obs/obs-plugins/obs-filters/locale/ar-SA.ini
/usr/share/obs/obs-plugins/obs-filters/locale/az-AZ.ini
/usr/share/obs/obs-plugins/obs-filters/locale/ba-RU.ini
/usr/share/obs/obs-plugins/obs-filters/locale/bg-BG.ini
/usr/share/obs/obs-plugins/obs-filters/locale/bn-BD.ini
/usr/share/obs/obs-plugins/obs-filters/locale/ca-ES.ini
/usr/share/obs/obs-plugins/obs-filters/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/obs-filters/locale/da-DK.ini
/usr/share/obs/obs-plugins/obs-filters/locale/de-DE.ini
/usr/share/obs/obs-plugins/obs-filters/locale/el-GR.ini
/usr/share/obs/obs-plugins/obs-filters/locale/en-GB.ini
/usr/share/obs/obs-plugins/obs-filters/locale/en-US.ini
/usr/share/obs/obs-plugins/obs-filters/locale/eo-UY.ini
/usr/share/obs/obs-plugins/obs-filters/locale/es-ES.ini
/usr/share/obs/obs-plugins/obs-filters/locale/et-EE.ini
/usr/share/obs/obs-plugins/obs-filters/locale/eu-ES.ini
/usr/share/obs/obs-plugins/obs-filters/locale/fa-IR.ini
/usr/share/obs/obs-plugins/obs-filters/locale/fi-FI.ini
/usr/share/obs/obs-plugins/obs-filters/locale/fil-PH.ini
/usr/share/obs/obs-plugins/obs-filters/locale/fr-FR.ini
/usr/share/obs/obs-plugins/obs-filters/locale/gd-GB.ini
/usr/share/obs/obs-plugins/obs-filters/locale/gl-ES.ini
/usr/share/obs/obs-plugins/obs-filters/locale/he-IL.ini
/usr/share/obs/obs-plugins/obs-filters/locale/hi-IN.ini
/usr/share/obs/obs-plugins/obs-filters/locale/hr-HR.ini
/usr/share/obs/obs-plugins/obs-filters/locale/hu-HU.ini
/usr/share/obs/obs-plugins/obs-filters/locale/id-ID.ini
/usr/share/obs/obs-plugins/obs-filters/locale/it-IT.ini
/usr/share/obs/obs-plugins/obs-filters/locale/ja-JP.ini
/usr/share/obs/obs-plugins/obs-filters/locale/ka-GE.ini
/usr/share/obs/obs-plugins/obs-filters/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/obs-filters/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/obs-filters/locale/ko-KR.ini
/usr/share/obs/obs-plugins/obs-filters/locale/ms-MY.ini
/usr/share/obs/obs-plugins/obs-filters/locale/nb-NO.ini
/usr/share/obs/obs-plugins/obs-filters/locale/nl-NL.ini
/usr/share/obs/obs-plugins/obs-filters/locale/nn-NO.ini
/usr/share/obs/obs-plugins/obs-filters/locale/pl-PL.ini
/usr/share/obs/obs-plugins/obs-filters/locale/pt-BR.ini
/usr/share/obs/obs-plugins/obs-filters/locale/pt-PT.ini
/usr/share/obs/obs-plugins/obs-filters/locale/ro-RO.ini
/usr/share/obs/obs-plugins/obs-filters/locale/ru-RU.ini
/usr/share/obs/obs-plugins/obs-filters/locale/si-LK.ini
/usr/share/obs/obs-plugins/obs-filters/locale/sk-SK.ini
/usr/share/obs/obs-plugins/obs-filters/locale/sl-SI.ini
/usr/share/obs/obs-plugins/obs-filters/locale/sr-CS.ini
/usr/share/obs/obs-plugins/obs-filters/locale/sr-SP.ini
/usr/share/obs/obs-plugins/obs-filters/locale/sv-SE.ini
/usr/share/obs/obs-plugins/obs-filters/locale/szl-PL.ini
/usr/share/obs/obs-plugins/obs-filters/locale/ta-IN.ini
/usr/share/obs/obs-plugins/obs-filters/locale/th-TH.ini
/usr/share/obs/obs-plugins/obs-filters/locale/tl-PH.ini
/usr/share/obs/obs-plugins/obs-filters/locale/tr-TR.ini
/usr/share/obs/obs-plugins/obs-filters/locale/uk-UA.ini
/usr/share/obs/obs-plugins/obs-filters/locale/vi-VN.ini
/usr/share/obs/obs-plugins/obs-filters/locale/zh-CN.ini
/usr/share/obs/obs-plugins/obs-filters/locale/zh-TW.ini
/usr/share/obs/obs-plugins/obs-filters/luma_key_filter.effect
/usr/share/obs/obs-plugins/obs-filters/luma_key_filter_v2.effect
/usr/share/obs/obs-plugins/obs-filters/mask_alpha_filter.effect
/usr/share/obs/obs-plugins/obs-filters/mask_color_filter.effect
/usr/share/obs/obs-plugins/obs-filters/sharpness.effect
/usr/share/obs/obs-plugins/obs-outputs/locale/ar-SA.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ba-RU.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/bg-BG.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/bn-BD.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ca-ES.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/da-DK.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/de-DE.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/el-GR.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/en-GB.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/en-US.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/es-ES.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/et-EE.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/eu-ES.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/fa-IR.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/fi-FI.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/fil-PH.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/fr-FR.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/gd-GB.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/gl-ES.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/he-IL.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/hi-IN.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/hr-HR.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/hu-HU.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/id-ID.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/it-IT.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ja-JP.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ka-GE.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ko-KR.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/mn-MN.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ms-MY.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/nb-NO.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/nl-NL.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/nn-NO.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/pl-PL.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/pt-BR.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/pt-PT.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ro-RO.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ru-RU.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/si-LK.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/sk-SK.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/sl-SI.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/sr-CS.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/sr-SP.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/sv-SE.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/szl-PL.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ta-IN.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/th-TH.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/tl-PH.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/tr-TR.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/uk-UA.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/ur-PK.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/vi-VN.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/zh-CN.ini
/usr/share/obs/obs-plugins/obs-outputs/locale/zh-TW.ini
/usr/share/obs/obs-plugins/obs-transitions/fade_to_color_transition.effect
/usr/share/obs/obs-plugins/obs-transitions/fade_transition.effect
/usr/share/obs/obs-plugins/obs-transitions/locale/ar-SA.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/ba-RU.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/bg-BG.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/bn-BD.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/ca-ES.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/da-DK.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/de-DE.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/el-GR.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/en-GB.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/en-US.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/es-ES.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/et-EE.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/eu-ES.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/fa-IR.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/fi-FI.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/fil-PH.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/fr-FR.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/gd-GB.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/gl-ES.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/he-IL.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/hi-IN.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/hr-HR.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/hu-HU.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/id-ID.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/it-IT.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/ja-JP.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/ka-GE.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/ko-KR.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/ms-MY.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/nb-NO.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/nl-NL.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/pl-PL.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/pt-BR.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/pt-PT.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/ro-RO.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/ru-RU.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/si-LK.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/sk-SK.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/sl-SI.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/sr-CS.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/sr-SP.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/sv-SE.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/szl-PL.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/ta-IN.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/tl-PH.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/tr-TR.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/uk-UA.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/vi-VN.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/zh-CN.ini
/usr/share/obs/obs-plugins/obs-transitions/locale/zh-TW.ini
/usr/share/obs/obs-plugins/obs-transitions/luma_wipe_transition.effect
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/barndoor-botleft.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/barndoor-h.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/barndoor-topleft.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/barndoor-v.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/blinds-h.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/box-botleft.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/box-botright.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/box-topleft.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/box-topright.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/burst.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/checkerboard-small.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/circles.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/clock.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/cloud.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/curtain.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/fan.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/fractal.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/iris.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/linear-h.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/linear-topleft.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/linear-topright.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/linear-v.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/parallel-zigzag-h.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/parallel-zigzag-v.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/sinus9.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/spiral.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/square.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/squares.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/stripes.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/strips-h.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/strips-v.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/watercolor.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/wipes.json
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/zigzag-h.png
/usr/share/obs/obs-plugins/obs-transitions/luma_wipes/zigzag-v.png
/usr/share/obs/obs-plugins/obs-transitions/slide_transition.effect
/usr/share/obs/obs-plugins/obs-transitions/stinger_matte_transition.effect
/usr/share/obs/obs-plugins/obs-transitions/swipe_transition.effect
/usr/share/obs/obs-plugins/rtmp-services/locale/ar-SA.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ba-RU.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/bg-BG.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/bn-BD.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ca-ES.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/da-DK.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/de-DE.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/el-GR.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/en-US.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/es-ES.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/et-EE.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/eu-ES.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/fa-IR.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/fi-FI.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/fil-PH.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/fr-FR.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/gd-GB.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/gl-ES.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/he-IL.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/hi-IN.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/hr-HR.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/hu-HU.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/id-ID.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/it-IT.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ja-JP.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ka-GE.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ko-KR.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/mn-MN.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ms-MY.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/nb-NO.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/nl-NL.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/nn-NO.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/pl-PL.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/pt-BR.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/pt-PT.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ro-RO.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ru-RU.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/si-LK.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/sk-SK.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/sl-SI.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/sr-CS.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/sr-SP.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/sv-SE.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/szl-PL.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ta-IN.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/th-TH.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/tl-PH.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/tr-TR.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/uk-UA.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/ur-PK.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/vi-VN.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/zh-CN.ini
/usr/share/obs/obs-plugins/rtmp-services/locale/zh-TW.ini
/usr/share/obs/obs-plugins/rtmp-services/package.json
/usr/share/obs/obs-plugins/rtmp-services/services.json
/usr/share/obs/obs-plugins/text-freetype2/locale/ar-SA.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/ba-RU.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/bg-BG.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/bn-BD.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/ca-ES.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/da-DK.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/de-DE.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/el-GR.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/en-GB.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/en-US.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/es-ES.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/et-EE.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/eu-ES.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/fa-IR.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/fi-FI.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/fil-PH.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/fr-FR.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/gd-GB.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/gl-ES.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/he-IL.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/hi-IN.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/hr-HR.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/hu-HU.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/id-ID.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/it-IT.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/ja-JP.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/ka-GE.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/ko-KR.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/mn-MN.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/ms-MY.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/nb-NO.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/nl-NL.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/nn-NO.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/pl-PL.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/pt-BR.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/pt-PT.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/ro-RO.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/ru-RU.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/si-LK.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/sk-SK.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/sl-SI.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/sr-CS.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/sr-SP.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/sv-SE.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/szl-PL.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/ta-IN.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/th-TH.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/tl-PH.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/tr-TR.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/uk-UA.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/vi-VN.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/zh-CN.ini
/usr/share/obs/obs-plugins/text-freetype2/locale/zh-TW.ini
/usr/share/obs/obs-plugins/text-freetype2/text_default.effect
/usr/share/obs/obs-plugins/vlc-video/locale/ar-SA.ini
/usr/share/obs/obs-plugins/vlc-video/locale/ba-RU.ini
/usr/share/obs/obs-plugins/vlc-video/locale/bg-BG.ini
/usr/share/obs/obs-plugins/vlc-video/locale/bn-BD.ini
/usr/share/obs/obs-plugins/vlc-video/locale/ca-ES.ini
/usr/share/obs/obs-plugins/vlc-video/locale/cs-CZ.ini
/usr/share/obs/obs-plugins/vlc-video/locale/da-DK.ini
/usr/share/obs/obs-plugins/vlc-video/locale/de-DE.ini
/usr/share/obs/obs-plugins/vlc-video/locale/el-GR.ini
/usr/share/obs/obs-plugins/vlc-video/locale/en-GB.ini
/usr/share/obs/obs-plugins/vlc-video/locale/en-US.ini
/usr/share/obs/obs-plugins/vlc-video/locale/es-ES.ini
/usr/share/obs/obs-plugins/vlc-video/locale/et-EE.ini
/usr/share/obs/obs-plugins/vlc-video/locale/eu-ES.ini
/usr/share/obs/obs-plugins/vlc-video/locale/fa-IR.ini
/usr/share/obs/obs-plugins/vlc-video/locale/fi-FI.ini
/usr/share/obs/obs-plugins/vlc-video/locale/fil-PH.ini
/usr/share/obs/obs-plugins/vlc-video/locale/fr-FR.ini
/usr/share/obs/obs-plugins/vlc-video/locale/gd-GB.ini
/usr/share/obs/obs-plugins/vlc-video/locale/gl-ES.ini
/usr/share/obs/obs-plugins/vlc-video/locale/he-IL.ini
/usr/share/obs/obs-plugins/vlc-video/locale/hi-IN.ini
/usr/share/obs/obs-plugins/vlc-video/locale/hr-HR.ini
/usr/share/obs/obs-plugins/vlc-video/locale/hu-HU.ini
/usr/share/obs/obs-plugins/vlc-video/locale/id-ID.ini
/usr/share/obs/obs-plugins/vlc-video/locale/it-IT.ini
/usr/share/obs/obs-plugins/vlc-video/locale/ja-JP.ini
/usr/share/obs/obs-plugins/vlc-video/locale/ka-GE.ini
/usr/share/obs/obs-plugins/vlc-video/locale/kab-KAB.ini
/usr/share/obs/obs-plugins/vlc-video/locale/kmr-TR.ini
/usr/share/obs/obs-plugins/vlc-video/locale/ko-KR.ini
/usr/share/obs/obs-plugins/vlc-video/locale/lt-LT.ini
/usr/share/obs/obs-plugins/vlc-video/locale/ms-MY.ini
/usr/share/obs/obs-plugins/vlc-video/locale/nb-NO.ini
/usr/share/obs/obs-plugins/vlc-video/locale/nl-NL.ini
/usr/share/obs/obs-plugins/vlc-video/locale/nn-NO.ini
/usr/share/obs/obs-plugins/vlc-video/locale/oc-FR.ini
/usr/share/obs/obs-plugins/vlc-video/locale/pl-PL.ini
/usr/share/obs/obs-plugins/vlc-video/locale/pt-BR.ini
/usr/share/obs/obs-plugins/vlc-video/locale/pt-PT.ini
/usr/share/obs/obs-plugins/vlc-video/locale/ro-RO.ini
/usr/share/obs/obs-plugins/vlc-video/locale/ru-RU.ini
/usr/share/obs/obs-plugins/vlc-video/locale/si-LK.ini
/usr/share/obs/obs-plugins/vlc-video/locale/sk-SK.ini
/usr/share/obs/obs-plugins/vlc-video/locale/sl-SI.ini
/usr/share/obs/obs-plugins/vlc-video/locale/sr-CS.ini
/usr/share/obs/obs-plugins/vlc-video/locale/sr-SP.ini
/usr/share/obs/obs-plugins/vlc-video/locale/sv-SE.ini
/usr/share/obs/obs-plugins/vlc-video/locale/szl-PL.ini
/usr/share/obs/obs-plugins/vlc-video/locale/ta-IN.ini
/usr/share/obs/obs-plugins/vlc-video/locale/tl-PH.ini
/usr/share/obs/obs-plugins/vlc-video/locale/tr-TR.ini
/usr/share/obs/obs-plugins/vlc-video/locale/uk-UA.ini
/usr/share/obs/obs-plugins/vlc-video/locale/vi-VN.ini
/usr/share/obs/obs-plugins/vlc-video/locale/zh-CN.ini
/usr/share/obs/obs-plugins/vlc-video/locale/zh-TW.ini
/usr/share/obs/obs-studio/authors/AUTHORS
/usr/share/obs/obs-studio/images/overflow.png
/usr/share/obs/obs-studio/license/gplv2.txt
/usr/share/obs/obs-studio/locale.ini
/usr/share/obs/obs-studio/locale/an-ES.ini
/usr/share/obs/obs-studio/locale/ar-SA.ini
/usr/share/obs/obs-studio/locale/az-AZ.ini
/usr/share/obs/obs-studio/locale/ba-RU.ini
/usr/share/obs/obs-studio/locale/bem-ZM.ini
/usr/share/obs/obs-studio/locale/bg-BG.ini
/usr/share/obs/obs-studio/locale/bn-BD.ini
/usr/share/obs/obs-studio/locale/ca-ES.ini
/usr/share/obs/obs-studio/locale/cs-CZ.ini
/usr/share/obs/obs-studio/locale/da-DK.ini
/usr/share/obs/obs-studio/locale/de-DE.ini
/usr/share/obs/obs-studio/locale/el-GR.ini
/usr/share/obs/obs-studio/locale/en-GB.ini
/usr/share/obs/obs-studio/locale/en-US.ini
/usr/share/obs/obs-studio/locale/eo-UY.ini
/usr/share/obs/obs-studio/locale/es-ES.ini
/usr/share/obs/obs-studio/locale/et-EE.ini
/usr/share/obs/obs-studio/locale/eu-ES.ini
/usr/share/obs/obs-studio/locale/fa-IR.ini
/usr/share/obs/obs-studio/locale/fi-FI.ini
/usr/share/obs/obs-studio/locale/fil-PH.ini
/usr/share/obs/obs-studio/locale/fr-FR.ini
/usr/share/obs/obs-studio/locale/gd-GB.ini
/usr/share/obs/obs-studio/locale/gl-ES.ini
/usr/share/obs/obs-studio/locale/he-IL.ini
/usr/share/obs/obs-studio/locale/hi-IN.ini
/usr/share/obs/obs-studio/locale/hr-HR.ini
/usr/share/obs/obs-studio/locale/hu-HU.ini
/usr/share/obs/obs-studio/locale/id-ID.ini
/usr/share/obs/obs-studio/locale/it-IT.ini
/usr/share/obs/obs-studio/locale/ja-JP.ini
/usr/share/obs/obs-studio/locale/ka-GE.ini
/usr/share/obs/obs-studio/locale/kab-KAB.ini
/usr/share/obs/obs-studio/locale/kmr-TR.ini
/usr/share/obs/obs-studio/locale/ko-KR.ini
/usr/share/obs/obs-studio/locale/lo-LA.ini
/usr/share/obs/obs-studio/locale/lt-LT.ini
/usr/share/obs/obs-studio/locale/lv-LV.ini
/usr/share/obs/obs-studio/locale/mn-MN.ini
/usr/share/obs/obs-studio/locale/ms-MY.ini
/usr/share/obs/obs-studio/locale/my-MM.ini
/usr/share/obs/obs-studio/locale/nb-NO.ini
/usr/share/obs/obs-studio/locale/nl-NL.ini
/usr/share/obs/obs-studio/locale/nn-NO.ini
/usr/share/obs/obs-studio/locale/oc-FR.ini
/usr/share/obs/obs-studio/locale/pa-IN.ini
/usr/share/obs/obs-studio/locale/pl-PL.ini
/usr/share/obs/obs-studio/locale/pt-BR.ini
/usr/share/obs/obs-studio/locale/pt-PT.ini
/usr/share/obs/obs-studio/locale/ro-RO.ini
/usr/share/obs/obs-studio/locale/ru-RU.ini
/usr/share/obs/obs-studio/locale/si-LK.ini
/usr/share/obs/obs-studio/locale/sk-SK.ini
/usr/share/obs/obs-studio/locale/sl-SI.ini
/usr/share/obs/obs-studio/locale/sq-AL.ini
/usr/share/obs/obs-studio/locale/sr-CS.ini
/usr/share/obs/obs-studio/locale/sr-SP.ini
/usr/share/obs/obs-studio/locale/sv-SE.ini
/usr/share/obs/obs-studio/locale/szl-PL.ini
/usr/share/obs/obs-studio/locale/ta-IN.ini
/usr/share/obs/obs-studio/locale/th-TH.ini
/usr/share/obs/obs-studio/locale/tl-PH.ini
/usr/share/obs/obs-studio/locale/tr-TR.ini
/usr/share/obs/obs-studio/locale/uk-UA.ini
/usr/share/obs/obs-studio/locale/ur-PK.ini
/usr/share/obs/obs-studio/locale/vi-VN.ini
/usr/share/obs/obs-studio/locale/zh-CN.ini
/usr/share/obs/obs-studio/locale/zh-TW.ini
/usr/share/obs/obs-studio/themes/Acri.qss
/usr/share/obs/obs-studio/themes/Acri/bot_hook.png
/usr/share/obs/obs-studio/themes/Acri/bot_hook2.png
/usr/share/obs/obs-studio/themes/Acri/checkbox_checked.png
/usr/share/obs/obs-studio/themes/Acri/checkbox_checked_disabled.png
/usr/share/obs/obs-studio/themes/Acri/checkbox_checked_focus.png
/usr/share/obs/obs-studio/themes/Acri/checkbox_unchecked.png
/usr/share/obs/obs-studio/themes/Acri/checkbox_unchecked_disabled.png
/usr/share/obs/obs-studio/themes/Acri/checkbox_unchecked_focus.png
/usr/share/obs/obs-studio/themes/Acri/radio_checked.png
/usr/share/obs/obs-studio/themes/Acri/radio_checked_disabled.png
/usr/share/obs/obs-studio/themes/Acri/radio_checked_focus.png
/usr/share/obs/obs-studio/themes/Acri/radio_unchecked.png
/usr/share/obs/obs-studio/themes/Acri/radio_unchecked_disabled.png
/usr/share/obs/obs-studio/themes/Acri/radio_unchecked_focus.png
/usr/share/obs/obs-studio/themes/Acri/sizegrip.png
/usr/share/obs/obs-studio/themes/Acri/top_hook.png
/usr/share/obs/obs-studio/themes/Dark.qss
/usr/share/obs/obs-studio/themes/Dark/alert.svg
/usr/share/obs/obs-studio/themes/Dark/close.svg
/usr/share/obs/obs-studio/themes/Dark/down.svg
/usr/share/obs/obs-studio/themes/Dark/expand.svg
/usr/share/obs/obs-studio/themes/Dark/filter.svg
/usr/share/obs/obs-studio/themes/Dark/interact.svg
/usr/share/obs/obs-studio/themes/Dark/left.svg
/usr/share/obs/obs-studio/themes/Dark/locked.svg
/usr/share/obs/obs-studio/themes/Dark/media-pause.svg
/usr/share/obs/obs-studio/themes/Dark/media/media_next.svg
/usr/share/obs/obs-studio/themes/Dark/media/media_pause.svg
/usr/share/obs/obs-studio/themes/Dark/media/media_play.svg
/usr/share/obs/obs-studio/themes/Dark/media/media_previous.svg
/usr/share/obs/obs-studio/themes/Dark/media/media_restart.svg
/usr/share/obs/obs-studio/themes/Dark/media/media_stop.svg
/usr/share/obs/obs-studio/themes/Dark/minus.svg
/usr/share/obs/obs-studio/themes/Dark/mute.svg
/usr/share/obs/obs-studio/themes/Dark/no_sources.svg
/usr/share/obs/obs-studio/themes/Dark/plus.svg
/usr/share/obs/obs-studio/themes/Dark/popout.svg
/usr/share/obs/obs-studio/themes/Dark/refresh.svg
/usr/share/obs/obs-studio/themes/Dark/revert.svg
/usr/share/obs/obs-studio/themes/Dark/save.svg
/usr/share/obs/obs-studio/themes/Dark/settings/advanced.svg
/usr/share/obs/obs-studio/themes/Dark/settings/audio.svg
/usr/share/obs/obs-studio/themes/Dark/settings/general.svg
/usr/share/obs/obs-studio/themes/Dark/settings/hotkeys.svg
/usr/share/obs/obs-studio/themes/Dark/settings/output.svg
/usr/share/obs/obs-studio/themes/Dark/settings/stream.svg
/usr/share/obs/obs-studio/themes/Dark/settings/video.svg
/usr/share/obs/obs-studio/themes/Dark/sources/brush.svg
/usr/share/obs/obs-studio/themes/Dark/sources/camera.svg
/usr/share/obs/obs-studio/themes/Dark/sources/default.svg
/usr/share/obs/obs-studio/themes/Dark/sources/gamepad.svg
/usr/share/obs/obs-studio/themes/Dark/sources/globe.svg
/usr/share/obs/obs-studio/themes/Dark/sources/group.svg
/usr/share/obs/obs-studio/themes/Dark/sources/image.svg
/usr/share/obs/obs-studio/themes/Dark/sources/media.svg
/usr/share/obs/obs-studio/themes/Dark/sources/microphone.svg
/usr/share/obs/obs-studio/themes/Dark/sources/scene.svg
/usr/share/obs/obs-studio/themes/Dark/sources/slideshow.svg
/usr/share/obs/obs-studio/themes/Dark/sources/text.svg
/usr/share/obs/obs-studio/themes/Dark/sources/window.svg
/usr/share/obs/obs-studio/themes/Dark/trash.svg
/usr/share/obs/obs-studio/themes/Dark/up.svg
/usr/share/obs/obs-studio/themes/Dark/updown.svg
/usr/share/obs/obs-studio/themes/Dark/visible.svg
/usr/share/obs/obs-studio/themes/Rachni.qss
/usr/share/obs/obs-studio/themes/Rachni/checkbox_checked.png
/usr/share/obs/obs-studio/themes/Rachni/checkbox_checked_disabled.png
/usr/share/obs/obs-studio/themes/Rachni/checkbox_checked_focus.png
/usr/share/obs/obs-studio/themes/Rachni/checkbox_unchecked.png
/usr/share/obs/obs-studio/themes/Rachni/checkbox_unchecked_disabled.png
/usr/share/obs/obs-studio/themes/Rachni/checkbox_unchecked_focus.png
/usr/share/obs/obs-studio/themes/Rachni/down_arrow.png
/usr/share/obs/obs-studio/themes/Rachni/down_arrow_disabled.png
/usr/share/obs/obs-studio/themes/Rachni/left_arrow.png
/usr/share/obs/obs-studio/themes/Rachni/left_arrow_disabled.png
/usr/share/obs/obs-studio/themes/Rachni/radio_checked.png
/usr/share/obs/obs-studio/themes/Rachni/radio_checked_disabled.png
/usr/share/obs/obs-studio/themes/Rachni/radio_checked_focus.png
/usr/share/obs/obs-studio/themes/Rachni/radio_unchecked.png
/usr/share/obs/obs-studio/themes/Rachni/radio_unchecked_disabled.png
/usr/share/obs/obs-studio/themes/Rachni/radio_unchecked_focus.png
/usr/share/obs/obs-studio/themes/Rachni/right_arrow.png
/usr/share/obs/obs-studio/themes/Rachni/right_arrow_disabled.png
/usr/share/obs/obs-studio/themes/Rachni/sizegrip.png
/usr/share/obs/obs-studio/themes/Rachni/up_arrow.png
/usr/share/obs/obs-studio/themes/Rachni/up_arrow_disabled.png
/usr/share/obs/obs-studio/themes/System.qss

%files dev
%defattr(-,root,root,-)
/usr/include/obs/audio-monitoring/pulse/pulseaudio-wrapper.h
/usr/include/obs/callback/calldata.h
/usr/include/obs/callback/decl.h
/usr/include/obs/callback/proc.h
/usr/include/obs/callback/signal.h
/usr/include/obs/graphics/axisang.h
/usr/include/obs/graphics/bounds.h
/usr/include/obs/graphics/device-exports.h
/usr/include/obs/graphics/effect-parser.h
/usr/include/obs/graphics/effect.h
/usr/include/obs/graphics/graphics-internal.h
/usr/include/obs/graphics/graphics.h
/usr/include/obs/graphics/half.h
/usr/include/obs/graphics/image-file.h
/usr/include/obs/graphics/input.h
/usr/include/obs/graphics/libnsgif/libnsgif.h
/usr/include/obs/graphics/math-defs.h
/usr/include/obs/graphics/math-extra.h
/usr/include/obs/graphics/matrix3.h
/usr/include/obs/graphics/matrix4.h
/usr/include/obs/graphics/plane.h
/usr/include/obs/graphics/quat.h
/usr/include/obs/graphics/shader-parser.h
/usr/include/obs/graphics/srgb.h
/usr/include/obs/graphics/vec2.h
/usr/include/obs/graphics/vec3.h
/usr/include/obs/graphics/vec4.h
/usr/include/obs/media-io/audio-io.h
/usr/include/obs/media-io/audio-math.h
/usr/include/obs/media-io/audio-resampler.h
/usr/include/obs/media-io/format-conversion.h
/usr/include/obs/media-io/frame-rate.h
/usr/include/obs/media-io/media-io-defs.h
/usr/include/obs/media-io/media-remux.h
/usr/include/obs/media-io/video-frame.h
/usr/include/obs/media-io/video-io.h
/usr/include/obs/media-io/video-scaler.h
/usr/include/obs/obs-audio-controls.h
/usr/include/obs/obs-avc.h
/usr/include/obs/obs-config.h
/usr/include/obs/obs-data.h
/usr/include/obs/obs-defs.h
/usr/include/obs/obs-encoder.h
/usr/include/obs/obs-ffmpeg-compat.h
/usr/include/obs/obs-frontend-api.h
/usr/include/obs/obs-hotkey.h
/usr/include/obs/obs-hotkeys.h
/usr/include/obs/obs-interaction.h
/usr/include/obs/obs-internal.h
/usr/include/obs/obs-missing-files.h
/usr/include/obs/obs-module.h
/usr/include/obs/obs-nix-platform.h
/usr/include/obs/obs-output.h
/usr/include/obs/obs-properties.h
/usr/include/obs/obs-scene.h
/usr/include/obs/obs-service.h
/usr/include/obs/obs-source.h
/usr/include/obs/obs-ui.h
/usr/include/obs/obs.h
/usr/include/obs/obs.hpp
/usr/include/obs/obsconfig.h
/usr/include/obs/util/array-serializer.h
/usr/include/obs/util/base.h
/usr/include/obs/util/bitstream.h
/usr/include/obs/util/bmem.h
/usr/include/obs/util/c99defs.h
/usr/include/obs/util/cf-lexer.h
/usr/include/obs/util/cf-parser.h
/usr/include/obs/util/circlebuf.h
/usr/include/obs/util/config-file.h
/usr/include/obs/util/crc32.h
/usr/include/obs/util/curl/curl-helper.h
/usr/include/obs/util/darray.h
/usr/include/obs/util/dstr.h
/usr/include/obs/util/file-serializer.h
/usr/include/obs/util/lexer.h
/usr/include/obs/util/pipe.h
/usr/include/obs/util/platform.h
/usr/include/obs/util/profiler.h
/usr/include/obs/util/profiler.hpp
/usr/include/obs/util/serializer.h
/usr/include/obs/util/simde/check.h
/usr/include/obs/util/simde/debug-trap.h
/usr/include/obs/util/simde/hedley.h
/usr/include/obs/util/simde/simde-align.h
/usr/include/obs/util/simde/simde-arch.h
/usr/include/obs/util/simde/simde-common.h
/usr/include/obs/util/simde/simde-constify.h
/usr/include/obs/util/simde/simde-detect-clang.h
/usr/include/obs/util/simde/simde-diagnostic.h
/usr/include/obs/util/simde/simde-features.h
/usr/include/obs/util/simde/simde-math.h
/usr/include/obs/util/simde/x86/mmx.h
/usr/include/obs/util/simde/x86/sse.h
/usr/include/obs/util/simde/x86/sse2.h
/usr/include/obs/util/sse-intrin.h
/usr/include/obs/util/task.h
/usr/include/obs/util/text-lookup.h
/usr/include/obs/util/threading-posix.h
/usr/include/obs/util/threading.h
/usr/include/obs/util/utf8.h
/usr/include/obs/util/util.hpp
/usr/include/obs/util/util_uint128.h
/usr/include/obs/util/util_uint64.h
/usr/lib64/cmake/LibObs/LibObsConfig.cmake
/usr/lib64/cmake/LibObs/LibObsConfigVersion.cmake
/usr/lib64/cmake/LibObs/LibObsTarget-relwithdebinfo.cmake
/usr/lib64/cmake/LibObs/LibObsTarget.cmake
/usr/lib64/libobs-frontend-api.so
/usr/lib64/libobs-opengl.so
/usr/lib64/libobs-scripting.so
/usr/lib64/libobs.so
/usr/lib64/libobsglad.so
/usr/lib64/pkgconfig/libobs.pc

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-obs-studio

%files lib
%defattr(-,root,root,-)
/usr/lib64/libobs-frontend-api.so.0
/usr/lib64/libobs-frontend-api.so.0.0
/usr/lib64/libobs-opengl.so.0
/usr/lib64/libobs-opengl.so.0.0
/usr/lib64/libobs.so.0
/usr/lib64/libobsglad.so.0
/usr/lib64/obs-plugins/decklink-captions.so
/usr/lib64/obs-plugins/decklink-ouput-ui.so
/usr/lib64/obs-plugins/frontend-tools.so
/usr/lib64/obs-plugins/image-source.so
/usr/lib64/obs-plugins/linux-alsa.so
/usr/lib64/obs-plugins/linux-capture.so
/usr/lib64/obs-plugins/linux-decklink.so
/usr/lib64/obs-plugins/linux-pulseaudio.so
/usr/lib64/obs-plugins/linux-v4l2.so
/usr/lib64/obs-plugins/obs-ffmpeg.so
/usr/lib64/obs-plugins/obs-filters.so
/usr/lib64/obs-plugins/obs-outputs.so
/usr/lib64/obs-plugins/obs-transitions.so
/usr/lib64/obs-plugins/rtmp-services.so
/usr/lib64/obs-plugins/text-freetype2.so
/usr/lib64/obs-plugins/vlc-video.so
/usr/lib64/obs-scripting/_obspython.so
/usr/lib64/obs-scripting/obslua.so
/usr/share/clear/optimized-elf/lib*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/obs-studio/0aeece1a03fbe9860ded71b2e17445209ad33c77
/usr/share/package-licenses/obs-studio/26a708b97cbb50e3fce8078dd21d65c8fdd5a605
/usr/share/package-licenses/obs-studio/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/obs-studio/53ae571e8630014de689edff14f755f16e5db8ed
/usr/share/package-licenses/obs-studio/5f8e73e1f293d0f127c2bcad2ab6fc5fa2a58139
/usr/share/package-licenses/obs-studio/6138ce06f16aef800693fb256090749acbabd038
/usr/share/package-licenses/obs-studio/6f68b53b3b12e5b75f296c54be785bc63e553d53
/usr/share/package-licenses/obs-studio/ac86b1d99268507a73261982375a5f47541247b1
/usr/share/package-licenses/obs-studio/d40d61b8fa8ecae46da12bd1fce4162af02cff8c
/usr/share/package-licenses/obs-studio/f6c7aa5a4f602a093c50a1d3328d1cb873ffdfc0
