#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v16
# autospec commit: b858a2a
#
Name     : obs-studio
Version  : 30.2.0
Release  : 66
URL      : https://github.com/obsproject/obs-studio/archive/30.2.0/obs-studio-30.2.0.tar.gz
Source0  : https://github.com/obsproject/obs-studio/archive/30.2.0/obs-studio-30.2.0.tar.gz
Source1  : https://github.com/microsoft/ftl-sdk/archive/d0c8469f66806b5ea738d607f7d2b000af8b1129.tar.gz
Source2  : https://github.com/obsproject/libdshowcapture/archive/ef8c1d2e19c93e664100dd41e1a0df4f8ad45430.tar.gz
Source3  : https://github.com/obsproject/obs-browser/archive/b4f724ae6abd371f8f0378f29c908f51065190f3.tar.gz
Source4  : https://github.com/obsproject/obs-websocket/archive/5b4aa9dabd26e488c3556ba83a92b9cef7a032c3.tar.gz
Summary  : OBS Studio frontend API library
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 GPL-2.0 ISC LGPL-2.1 MIT
BuildRequires : QR-Code-generator-dev
BuildRequires : Vulkan-Headers-dev Vulkan-Loader-dev Vulkan-Tools
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : curl-dev
BuildRequires : extra-cmake-modules pkgconfig(libpulse)
BuildRequires : extra-cmake-modules pkgconfig(wayland-client)
BuildRequires : extra-cmake-modules pkgconfig(x11-xcb)
BuildRequires : extra-cmake-modules pkgconfig(xcb) xcb-util-cursor-dev xcb-util-image-dev xcb-util-keysyms-dev xcb-util-renderutil-dev xcb-util-wm-dev xcb-util-dev
BuildRequires : freetype-dev
BuildRequires : glibc-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libajantv2-dev
BuildRequires : libdatachannel-dev
BuildRequires : mesa-dev
BuildRequires : nlohmann_json-dev
BuildRequires : not-ffmpeg-dev
BuildRequires : oneVPL-dev
BuildRequires : pipewire-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt6Svg)
BuildRequires : pkgconfig(Qt6Widgets)
BuildRequires : pkgconfig(asio)
BuildRequires : pkgconfig(fdk-aac)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(jack)
BuildRequires : pkgconfig(jansson)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libpci)
BuildRequires : pkgconfig(librist)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libvlc)
BuildRequires : pkgconfig(luajit)
BuildRequires : pkgconfig(mbedcrypto)
BuildRequires : pkgconfig(mbedtls)
BuildRequires : pkgconfig(mbedx509)
BuildRequires : pkgconfig(sndio)
BuildRequires : pkgconfig(speexdsp)
BuildRequires : pkgconfig(srt)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-server)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(x264)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(zlib)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qt6base-dev
BuildRequires : speex-dev
BuildRequires : speexdsp-dev
BuildRequires : swig
BuildRequires : uthash-dev
BuildRequires : v4l-utils-dev
BuildRequires : websocketpp-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-plugin-installation-path.patch
Patch2: 0002-obs-studio-change-default-config-to-ffmpeg.patch
Patch3: 0003-Fix-submake.patch
Patch4: 0004-Fix-AJANTV2-includes-in-backport-patch.patch

%description
PTHREADS-WIN32
==============
Pthreads-win32 is free software, distributed under the GNU Lesser
General Public License (LGPL). See the file 'COPYING.LIB' for terms
and conditions. Also see the file 'COPYING' for information
specific to pthreads-win32, copyrights and the LGPL.

%prep
%setup -q -n obs-studio-30.2.0
cd %{_builddir}
tar xf %{_sourcedir}/ef8c1d2e19c93e664100dd41e1a0df4f8ad45430.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b4f724ae6abd371f8f0378f29c908f51065190f3.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/d0c8469f66806b5ea738d607f7d2b000af8b1129.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/5b4aa9dabd26e488c3556ba83a92b9cef7a032c3.tar.gz
cd %{_builddir}/obs-studio-30.2.0
mkdir -p plugins/win-dshow/libdshowcapture
cp -r %{_builddir}/libdshowcapture-ef8c1d2e19c93e664100dd41e1a0df4f8ad45430/* %{_builddir}/obs-studio-30.2.0/plugins/win-dshow/libdshowcapture
mkdir -p plugins/obs-browser
cp -r %{_builddir}/obs-browser-b4f724ae6abd371f8f0378f29c908f51065190f3/* %{_builddir}/obs-studio-30.2.0/plugins/obs-browser
mkdir -p plugins/obs-outputs/ftl-sdk
cp -r %{_builddir}/ftl-sdk-d0c8469f66806b5ea738d607f7d2b000af8b1129/* %{_builddir}/obs-studio-30.2.0/plugins/obs-outputs/ftl-sdk
mkdir -p plugins/obs-websocket
cp -r %{_builddir}/obs-websocket-5b4aa9dabd26e488c3556ba83a92b9cef7a032c3/* %{_builddir}/obs-studio-30.2.0/plugins/obs-websocket
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
pushd ..
cp -a obs-studio-30.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721239661
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DBUILD_BROWSER=OFF \
-DENABLE_JACK=ON \
-DENABLE_LIBFDK=ON \
-DENABLE_SNDIO=ON \
-DOBS_MULTIARCH_SUFFIX=64 \
-DOBS_VERSION_OVERRIDE="%{version}-%{release}"  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DBUILD_BROWSER=OFF \
-DENABLE_JACK=ON \
-DENABLE_LIBFDK=ON \
-DENABLE_SNDIO=ON \
-DOBS_MULTIARCH_SUFFIX=64 \
-DOBS_VERSION_OVERRIDE="%{version}-%{release}"  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1721239661
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/obs-studio
cp %{_builddir}/ftl-sdk-d0c8469f66806b5ea738d607f7d2b000af8b1129/LICENSE %{buildroot}/usr/share/package-licenses/obs-studio/ee78578e91b465f4bf4c5728a22c564e55ad59f6 || :
cp %{_builddir}/libdshowcapture-ef8c1d2e19c93e664100dd41e1a0df4f8ad45430/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/obs-browser-b4f724ae6abd371f8f0378f29c908f51065190f3/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/dfac199a7539a404407098a2541b9482279f690d || :
cp %{_builddir}/obs-studio-%{version}/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/obs-studio-%{version}/UI/data/license/gplv2.txt %{buildroot}/usr/share/package-licenses/obs-studio/53ae571e8630014de689edff14f755f16e5db8ed || :
cp %{_builddir}/obs-studio-%{version}/UI/data/license/gplv2.txt %{buildroot}/usr/share/package-licenses/obs-studio/53ae571e8630014de689edff14f755f16e5db8ed || :
cp %{_builddir}/obs-studio-%{version}/deps/blake2/LICENSE.blake2 %{buildroot}/usr/share/package-licenses/obs-studio/148d1cf7220659006b5d5e03263b7c40ad6a9a3a || :
cp %{_builddir}/obs-studio-%{version}/deps/json11/LICENSE.txt %{buildroot}/usr/share/package-licenses/obs-studio/d40d61b8fa8ecae46da12bd1fce4162af02cff8c || :
cp %{_builddir}/obs-studio-%{version}/deps/libcaption/LICENSE.txt %{buildroot}/usr/share/package-licenses/obs-studio/ac86b1d99268507a73261982375a5f47541247b1 || :
cp %{_builddir}/obs-studio-%{version}/deps/media-playback/LICENSE.media-playback %{buildroot}/usr/share/package-licenses/obs-studio/b301afd1148e3c3631e9352ef19eb9c667707eb9 || :
cp %{_builddir}/obs-studio-%{version}/deps/w32-pthreads/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/0aeece1a03fbe9860ded71b2e17445209ad33c77 || :
cp %{_builddir}/obs-studio-%{version}/deps/w32-pthreads/COPYING.LIB %{buildroot}/usr/share/package-licenses/obs-studio/f6c7aa5a4f602a093c50a1d3328d1cb873ffdfc0 || :
cp %{_builddir}/obs-studio-%{version}/libobs/graphics/libnsgif/LICENSE.libnsgif %{buildroot}/usr/share/package-licenses/obs-studio/2e4be4b425e6099d28a6822a0b04740a922a0587 || :
cp %{_builddir}/obs-studio-%{version}/libobs/util/simde/LICENSE.simde %{buildroot}/usr/share/package-licenses/obs-studio/1528e23fe952214a0939024727ed9ad218d742c4 || :
cp %{_builddir}/obs-studio-%{version}/plugins/decklink/LICENSE.decklink-sdk %{buildroot}/usr/share/package-licenses/obs-studio/4b42d99a3282f3d7071bdcc1f742a0d05c7ea7c0 || :
cp %{_builddir}/obs-studio-%{version}/plugins/mac-syphon/data/syphon_license.txt %{buildroot}/usr/share/package-licenses/obs-studio/6f68b53b3b12e5b75f296c54be785bc63e553d53 || :
cp %{_builddir}/obs-studio-%{version}/plugins/obs-filters/rnnoise/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/5f8e73e1f293d0f127c2bcad2ab6fc5fa2a58139 || :
cp %{_builddir}/obs-studio-%{version}/plugins/obs-outputs/librtmp/COPYING %{buildroot}/usr/share/package-licenses/obs-studio/6138ce06f16aef800693fb256090749acbabd038 || :
cp %{_builddir}/obs-studio-%{version}/plugins/obs-qsv11/obs-qsv11-LICENSE.txt %{buildroot}/usr/share/package-licenses/obs-studio/5cd1064384e731cce71df85f2c74bfb6f2756644 || :
cp %{_builddir}/obs-websocket-5b4aa9dabd26e488c3556ba83a92b9cef7a032c3/LICENSE %{buildroot}/usr/share/package-licenses/obs-studio/e34353da7128500175862c3eef1c3ff89f83eecd || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
